language: node_js

node_js:
  - '9'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    cd build;
    \cp index.html 404.html;
    git init;
    git config user.name 'Travis CI';
    git config user.email 'i@zhuweiyou.com';
    git add .;
    git commit -m 'build';
    git push https://${GH_TOKEN}@github.com/zhuweiyou/zhuweiyou.com.git master:gh-pages -f;
    fi

branches:
  only:
    - master
